### ISSUE TITLE
Highscore not updating

### ISSUE THREAD

**Issue by kenroy** [MichaelJFordham/playdate-game-demo#3]
I worked through the tutorial and the highscore doesn't update. It looks like scoreTable is not being saved. I also downloaded the code from here and it's the same problem. Highscore works in the game downloaded from itch.io though. Any idea what I could be doing wrong? Thanks.

**Comment by MichaelJFordham** [comment]
Hey @kenroy 

Thanks for raising this as an issue. I hadn't noticed that until now. The problem was that the saveScore function was not being called when the ball collided with the goal. I have pushed a fix to the main branch now which resolves this. Hope that helps!
